#!/usr/bin/env python
"""W2: render results/y3_w2/diag.json as the diagnostic table for the report.

The diagnostic is a LOSS comparison on ONE fixed decision stream (generated by
the shipped squared-error decider), so every row differs only in the objective,
the inputs and the optimiser setting -- not in the trajectory it was fitted on.
It answers "is a negative result about the objective or about the optimiser?"
and it selects each objective's learning rate on VALIDATION loss alone.
"""

import argparse
import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)

import numpy as np                                              # noqa: E402

import y3_w2_lib as L                                           # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=os.path.join(L.OUT, "diag.json"))
    a = ap.parse_args()
    d = json.load(open(a.src))
    runs = d["runs"]

    print("fixed decision stream: %r" % d["dataset"])
    print("split (by instance): train=%d val=%d decisions; overrides %d/%d"
          % (d["n_train_dec"], d["n_val_dec"], d["n_train_ov"], d["n_val_ov"]))
    print()
    hdr = ("%-10s %-6s %-7s %-5s %-6s %-15s %-7s %8s %7s %7s %7s %7s %8s %6s"
           % ("objective", "queue", "lr", "batch", "delta", "data", "tau-fix",
              "val", "Pearson", "signAcc", "mean_s", "sd_s", "valLL", "top1"))
    print(hdr); print("-" * len(hdr))
    for r in runs:
        print("%-10s %-6s %-7g %-5d %-6s %-15s %-7s %8.4f %+7.3f %7.3f %+7.3f "
              "%7.3f %8.3f %6.3f"
              % (r["objective"], r["use_queue"], r["lr"], r["batch"],
                 r["delta"], r["data"], r.get("tau_fixed", False),
                 r["best_val"], r["pearson_r"], r["sign_acc_nonzero"],
                 r["mean_hat_s"], r.get("sd_hat_s", float("nan")),
                 r["val_choice_ll"], r["val_top1"]))

    print()
    print("SELECTED learning rate per objective (lowest VALIDATION loss, "
          "per-order inputs, batch 512, full data):")
    for obj in ("mse", "choice", "tolerance"):
        cand = [r for r in runs if r["objective"] == obj and r["batch"] == 512
                and r["data"] == "all" and not r.get("tau_fixed")
                and not r["use_queue"]]
        if not cand:
            continue
        best = min(cand, key=lambda r: r["best_val"])
        print("  %-10s lr=%-7g val=%.4f   (%s)" % (
            obj, best["lr"], best["best_val"],
            ", ".join("%g:%.4f" % (r["lr"], r["best_val"]) for r in cand)))

    print()
    print("Does the choice loss just want more gradient steps? (batch 128 vs 512)")
    for uq in (False, True):
        rows = [r for r in runs if r["objective"] == "choice" and r["data"] == "all"
                and not r.get("tau_fixed") and r["use_queue"] == uq]
        for b in (512, 128):
            sel = [r for r in rows if r["batch"] == b]
            if sel:
                bst = min(sel, key=lambda r: r["best_val"])
                print("  queue=%-5s batch %3d: val %.4f  Pearson %+.3f  sign %.3f"
                      % (uq, b, bst["best_val"], bst["pearson_r"],
                         bst["sign_acc_nonzero"]))

    print()
    print("Is the CONFIRMATION term the problem? (overrides-only removes it)")
    for uq in (False, True):
        for data in ("all", "overrides_only"):
            sel = [r for r in runs if r["objective"] == "choice" and r["batch"] == 512
                   and r["data"] == data and r["use_queue"] == uq
                   and not r.get("tau_fixed")]
            if sel:
                bst = min(sel, key=lambda r: r["best_val"])
                print("  queue=%-5s %-15s Pearson %+.3f  sign %.3f  sd_s %.3f"
                      % (uq, data, bst["pearson_r"], bst["sign_acc_nonzero"],
                         bst.get("sd_hat_s", float("nan"))))

    print()
    print("Tolerance-aware confirmations (a confirmation certifies a near-tie, "
          "not a choice):")
    for r in [x for x in runs if x["objective"] == "tolerance"]:
        print("  delta=%-5s queue=%-5s  Pearson %+.3f  sign %.3f  sd_s %.3f  "
              "valLL %.3f" % (r["delta"], r["use_queue"], r["pearson_r"],
                              r["sign_acc_nonzero"],
                              r.get("sd_hat_s", float("nan")),
                              r["val_choice_ll"]))

    print()
    print("Frozen choice scale (removes the s_hat-scale / tau degeneracy):")
    for r in [x for x in runs if x.get("tau_fixed")]:
        print("  queue=%-5s  Pearson %+.3f  sign %.3f  sd_s %.3f  tau %.3f"
              % (r["use_queue"], r["pearson_r"], r["sign_acc_nonzero"],
                 r.get("sd_hat_s", float("nan")), r["tau_final"]))


if __name__ == "__main__":
    sys.exit(main())
